#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABELLANA_NATIONAL_SCHOOL_FINAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ANS_DATABASE")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_PARENT(TBL_PARENT instance);
    partial void UpdateTBL_PARENT(TBL_PARENT instance);
    partial void DeleteTBL_PARENT(TBL_PARENT instance);
    partial void InsertTBL_USERTYPE(TBL_USERTYPE instance);
    partial void UpdateTBL_USERTYPE(TBL_USERTYPE instance);
    partial void DeleteTBL_USERTYPE(TBL_USERTYPE instance);
    partial void InsertTBL_SECURITY(TBL_SECURITY instance);
    partial void UpdateTBL_SECURITY(TBL_SECURITY instance);
    partial void DeleteTBL_SECURITY(TBL_SECURITY instance);
    partial void InsertTBL_STUDENT(TBL_STUDENT instance);
    partial void UpdateTBL_STUDENT(TBL_STUDENT instance);
    partial void DeleteTBL_STUDENT(TBL_STUDENT instance);
    partial void InsertTBL_USER(TBL_USER instance);
    partial void UpdateTBL_USER(TBL_USER instance);
    partial void DeleteTBL_USER(TBL_USER instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ABELLANA_NATIONAL_SCHOOL_FINAL.Properties.Settings.Default.ANS_DATABASEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_PARENT> TBL_PARENTs
		{
			get
			{
				return this.GetTable<TBL_PARENT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USERTYPE> TBL_USERTYPEs
		{
			get
			{
				return this.GetTable<TBL_USERTYPE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_SECURITY> TBL_SECURITies
		{
			get
			{
				return this.GetTable<TBL_SECURITY>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STUDENT> TBL_STUDENTs
		{
			get
			{
				return this.GetTable<TBL_STUDENT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USER> TBL_USERs
		{
			get
			{
				return this.GetTable<TBL_USER>();
			}
		}
		
		public System.Data.Linq.Table<View_STANDPT> View_STANDPTs
		{
			get
			{
				return this.GetTable<View_STANDPT>();
			}
		}
		
		public System.Data.Linq.Table<View_User> View_Users
		{
			get
			{
				return this.GetTable<View_User>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACCOUNTRECOVERY")]
		public ISingleResult<SP_ACCOUNTRECOVERYResult> SP_ACCOUNTRECOVERY([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_USERNAME", DbType="VarChar(50)")] string uSER_USERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECU_QUESTION", DbType="VarChar(50)")] string sECU_QUESTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECU_ANSWER", DbType="VarChar(50)")] string sECU_ANSWER)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_USERNAME, sECU_QUESTION, sECU_ANSWER);
			return ((ISingleResult<SP_ACCOUNTRECOVERYResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ST_CURRENTID")]
		public int ST_CURRENTID()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CHANGEDEFAULTPASS")]
		public int SP_CHANGEDEFAULTPASS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_USERNAME", DbType="VarChar(50)")] string uSER_USERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PASSWORD", DbType="VarChar(50)")] string uSER_PASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID, uSER_USERNAME, uSER_PASSWORD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CHANGEUSERPASS")]
		public int SP_CHANGEUSERPASS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_USERNAME", DbType="VarChar(50)")] string uSER_USERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PASSWORD", DbType="VarChar(50)")] string uSER_PASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_USERNAME, uSER_PASSWORD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SECUSAVE")]
		public int SP_SECUSAVE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECU_QUESTION", DbType="VarChar(50)")] string sECU_QUESTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECU_ANSWER", DbType="VarChar(50)")] string sECU_ANSWER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sECU_QUESTION, sECU_ANSWER, uSER_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_STSAVE")]
		public int SP_STSAVE(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_CURRENTID", DbType="VarChar(50)")] string sT_CURRENTID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_FIRSTNAME", DbType="VarChar(50)")] string sT_FIRSTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_MIDDLENAME", DbType="VarChar(50)")] string sT_MIDDLENAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_LASTNAME", DbType="VarChar(50)")] string sT_LASTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_YEARLEVEL", DbType="VarChar(50)")] string sT_YEARLEVEL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_SCHOOLYEAR", DbType="VarChar(50)")] string sT_SCHOOLYEAR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_BIRTHDATE", DbType="Date")] System.Nullable<System.DateTime> sT_BIRTHDATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_AGE", DbType="Int")] System.Nullable<int> sT_AGE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_BIRTHPLACE", DbType="VarChar(50)")] string sT_BIRTHPLACE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_ADDRESS", DbType="VarChar(50)")] string sT_ADDRESS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_GENDER", DbType="VarChar(50)")] string sT_GENDER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_CONTACTNUMBER", DbType="VarChar(50)")] string sT_CONTACTNUMBER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_HEIGHT", DbType="Float")] System.Nullable<double> sT_HEIGHT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_WEIGHT", DbType="Float")] System.Nullable<double> sT_WEIGHT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_BLOODPRESSURE", DbType="VarChar(50)")] string sT_BLOODPRESSURE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAME", DbType="VarChar(50)")] string nAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_CONTACT", DbType="VarChar(50)")] string p_CONTACT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_OCCUPATION", DbType="VarChar(50)")] string p_OCCUPATION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sT_CURRENTID, sT_FIRSTNAME, sT_MIDDLENAME, sT_LASTNAME, sT_YEARLEVEL, sT_SCHOOLYEAR, sT_BIRTHDATE, sT_AGE, sT_BIRTHPLACE, sT_ADDRESS, sT_GENDER, sT_CONTACTNUMBER, sT_HEIGHT, sT_WEIGHT, sT_BLOODPRESSURE, nAME, p_CONTACT, p_OCCUPATION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_STSEARCH")]
		public ISingleResult<SP_STSEARCHResult> SP_STSEARCH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEARCH_KEY", DbType="VarChar(MAX)")] string sEARCH_KEY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sEARCH_KEY);
			return ((ISingleResult<SP_STSEARCHResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_STUPDATE")]
		public int SP_STUPDATE(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_ID", DbType="Int")] System.Nullable<int> sT_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_FIRSTNAME", DbType="VarChar(50)")] string sT_FIRSTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_MIDDLENAME", DbType="VarChar(50)")] string sT_MIDDLENAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_LASTNAME", DbType="VarChar(50)")] string sT_LASTNAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_YEARLEVEL", DbType="VarChar(50)")] string sT_YEARLEVEL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_SCHOOLYEAR", DbType="VarChar(50)")] string sT_SCHOOLYEAR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_BIRTHDATE", DbType="Date")] System.Nullable<System.DateTime> sT_BIRTHDATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_AGE", DbType="Int")] System.Nullable<int> sT_AGE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_BIRTHPLACE", DbType="VarChar(50)")] string sT_BIRTHPLACE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_ADDRESS", DbType="VarChar(50)")] string sT_ADDRESS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_GENDER", DbType="VarChar(50)")] string sT_GENDER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_CONTACTNUMBER", DbType="VarChar(50)")] string sT_CONTACTNUMBER, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISACTIVE", DbType="Bit")] System.Nullable<bool> iSACTIVE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_HEIGHT", DbType="Float")] System.Nullable<double> sT_HEIGHT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_WEIGHT", DbType="Float")] System.Nullable<double> sT_WEIGHT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ST_BLOODPRESSURE", DbType="VarChar(50)")] string sT_BLOODPRESSURE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_ID", DbType="Int")] System.Nullable<int> p_ID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_NAME", DbType="VarChar(50)")] string p_NAME, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_CONTACT", DbType="VarChar(50)")] string p_CONTACT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="P_OCCUPATION", DbType="VarChar(50)")] string p_OCCUPATION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sT_ID, sT_FIRSTNAME, sT_MIDDLENAME, sT_LASTNAME, sT_YEARLEVEL, sT_SCHOOLYEAR, sT_BIRTHDATE, sT_AGE, sT_BIRTHPLACE, sT_ADDRESS, sT_GENDER, sT_CONTACTNUMBER, iSACTIVE, sT_HEIGHT, sT_WEIGHT, sT_BLOODPRESSURE, p_ID, p_NAME, p_CONTACT, p_OCCUPATION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_STVIEW")]
		public ISingleResult<SP_STVIEWResult> SP_STVIEW()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_STVIEWResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_USERSAVE")]
		public int SP_USERSAVE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_LASTNAME", DbType="VarChar(50)")] string uSER_LASTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_FIRSTNAME", DbType="VarChar(50)")] string uSER_FIRSTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_MIDDLENAME", DbType="VarChar(50)")] string uSER_MIDDLENAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_USERNAME", DbType="VarChar(50)")] string uSER_USERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PASSWORD", DbType="VarChar(50)")] string uSER_PASSWORD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CONTACTNO", DbType="VarChar(50)")] string uSER_CONTACTNO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_CREATOR", DbType="VarChar(50)")] string uSER_CREATOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_TYPE", DbType="Int")] System.Nullable<int> uSER_TYPE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_IMAGE", DbType="VarChar(MAX)")] string uSER_IMAGE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_LASTNAME, uSER_FIRSTNAME, uSER_MIDDLENAME, uSER_USERNAME, uSER_PASSWORD, uSER_CONTACTNO, uSER_CREATOR, uSER_TYPE, uSER_IMAGE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_USERSEARCH")]
		public ISingleResult<SP_USERSEARCHResult> SP_USERSEARCH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEARCHKEY", DbType="VarChar(MAX)")] string sEARCHKEY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sEARCHKEY);
			return ((ISingleResult<SP_USERSEARCHResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_USERUPDATE")]
		public int SP_USERUPDATE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_LASTNAME", DbType="VarChar(50)")] string uSER_LASTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_FIRSTNAME", DbType="VarChar(50)")] string uSER_FIRSTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_MIDDLENAME", DbType="VarChar(50)")] string uSER_MIDDLENAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_USERNAME", DbType="VarChar(50)")] string uSER_USERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISACTIVE", DbType="Bit")] System.Nullable<bool> iSACTIVE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_IMAGE", DbType="VarChar(MAX)")] string uSER_IMAGE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID, uSER_LASTNAME, uSER_FIRSTNAME, uSER_MIDDLENAME, uSER_USERNAME, iSACTIVE, uSER_IMAGE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_USERVIEW")]
		public ISingleResult<SP_USERVIEWResult> SP_USERVIEW()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_USERVIEWResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VERIFYPASSWORD")]
		public ISingleResult<SP_VERIFYPASSWORDResult> SP_VERIFYPASSWORD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_PASSWORD", DbType="VarChar(50)")] string uSER_PASSWORD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID, uSER_PASSWORD);
			return ((ISingleResult<SP_VERIFYPASSWORDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PARENT")]
	public partial class TBL_PARENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _P_ID;
		
		private string _P_NAME;
		
		private string _P_CONTACT;
		
		private string _P_OCCUPATION;
		
		private EntitySet<TBL_STUDENT> _TBL_STUDENTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_IDChanging(int value);
    partial void OnP_IDChanged();
    partial void OnP_NAMEChanging(string value);
    partial void OnP_NAMEChanged();
    partial void OnP_CONTACTChanging(string value);
    partial void OnP_CONTACTChanged();
    partial void OnP_OCCUPATIONChanging(string value);
    partial void OnP_OCCUPATIONChanged();
    #endregion
		
		public TBL_PARENT()
		{
			this._TBL_STUDENTs = new EntitySet<TBL_STUDENT>(new Action<TBL_STUDENT>(this.attach_TBL_STUDENTs), new Action<TBL_STUDENT>(this.detach_TBL_STUDENTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_NAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_NAME
		{
			get
			{
				return this._P_NAME;
			}
			set
			{
				if ((this._P_NAME != value))
				{
					this.OnP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._P_NAME = value;
					this.SendPropertyChanged("P_NAME");
					this.OnP_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_CONTACT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_CONTACT
		{
			get
			{
				return this._P_CONTACT;
			}
			set
			{
				if ((this._P_CONTACT != value))
				{
					this.OnP_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._P_CONTACT = value;
					this.SendPropertyChanged("P_CONTACT");
					this.OnP_CONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_OCCUPATION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_OCCUPATION
		{
			get
			{
				return this._P_OCCUPATION;
			}
			set
			{
				if ((this._P_OCCUPATION != value))
				{
					this.OnP_OCCUPATIONChanging(value);
					this.SendPropertyChanging();
					this._P_OCCUPATION = value;
					this.SendPropertyChanged("P_OCCUPATION");
					this.OnP_OCCUPATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PARENT_TBL_STUDENT", Storage="_TBL_STUDENTs", ThisKey="P_ID", OtherKey="P_ID")]
		public EntitySet<TBL_STUDENT> TBL_STUDENTs
		{
			get
			{
				return this._TBL_STUDENTs;
			}
			set
			{
				this._TBL_STUDENTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_STUDENTs(TBL_STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PARENT = this;
		}
		
		private void detach_TBL_STUDENTs(TBL_STUDENT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_PARENT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USERTYPE")]
	public partial class TBL_USERTYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USER_TYPEID;
		
		private string _USER_TYPE;
		
		private EntitySet<TBL_USER> _TBL_USERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSER_TYPEIDChanging(int value);
    partial void OnUSER_TYPEIDChanged();
    partial void OnUSER_TYPEChanging(string value);
    partial void OnUSER_TYPEChanged();
    #endregion
		
		public TBL_USERTYPE()
		{
			this._TBL_USERs = new EntitySet<TBL_USER>(new Action<TBL_USER>(this.attach_TBL_USERs), new Action<TBL_USER>(this.detach_TBL_USERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPEID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int USER_TYPEID
		{
			get
			{
				return this._USER_TYPEID;
			}
			set
			{
				if ((this._USER_TYPEID != value))
				{
					this.OnUSER_TYPEIDChanging(value);
					this.SendPropertyChanging();
					this._USER_TYPEID = value;
					this.SendPropertyChanged("USER_TYPEID");
					this.OnUSER_TYPEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPE", DbType="VarChar(50)")]
		public string USER_TYPE
		{
			get
			{
				return this._USER_TYPE;
			}
			set
			{
				if ((this._USER_TYPE != value))
				{
					this.OnUSER_TYPEChanging(value);
					this.SendPropertyChanging();
					this._USER_TYPE = value;
					this.SendPropertyChanged("USER_TYPE");
					this.OnUSER_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_USERTYPE_TBL_USER", Storage="_TBL_USERs", ThisKey="USER_TYPEID", OtherKey="USER_TYPEID")]
		public EntitySet<TBL_USER> TBL_USERs
		{
			get
			{
				return this._TBL_USERs;
			}
			set
			{
				this._TBL_USERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_USERs(TBL_USER entity)
		{
			this.SendPropertyChanging();
			entity.TBL_USERTYPE = this;
		}
		
		private void detach_TBL_USERs(TBL_USER entity)
		{
			this.SendPropertyChanging();
			entity.TBL_USERTYPE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_SECURITY")]
	public partial class TBL_SECURITY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SECU_ID;
		
		private string _SECU_QUESTION;
		
		private string _SECU_ANSWER;
		
		private System.Nullable<int> _USER_ID;
		
		private EntityRef<TBL_USER> _TBL_USER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSECU_IDChanging(int value);
    partial void OnSECU_IDChanged();
    partial void OnSECU_QUESTIONChanging(string value);
    partial void OnSECU_QUESTIONChanged();
    partial void OnSECU_ANSWERChanging(string value);
    partial void OnSECU_ANSWERChanged();
    partial void OnUSER_IDChanging(System.Nullable<int> value);
    partial void OnUSER_IDChanged();
    #endregion
		
		public TBL_SECURITY()
		{
			this._TBL_USER = default(EntityRef<TBL_USER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECU_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SECU_ID
		{
			get
			{
				return this._SECU_ID;
			}
			set
			{
				if ((this._SECU_ID != value))
				{
					this.OnSECU_IDChanging(value);
					this.SendPropertyChanging();
					this._SECU_ID = value;
					this.SendPropertyChanged("SECU_ID");
					this.OnSECU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECU_QUESTION", DbType="VarChar(50)")]
		public string SECU_QUESTION
		{
			get
			{
				return this._SECU_QUESTION;
			}
			set
			{
				if ((this._SECU_QUESTION != value))
				{
					this.OnSECU_QUESTIONChanging(value);
					this.SendPropertyChanging();
					this._SECU_QUESTION = value;
					this.SendPropertyChanged("SECU_QUESTION");
					this.OnSECU_QUESTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECU_ANSWER", DbType="VarChar(50)")]
		public string SECU_ANSWER
		{
			get
			{
				return this._SECU_ANSWER;
			}
			set
			{
				if ((this._SECU_ANSWER != value))
				{
					this.OnSECU_ANSWERChanging(value);
					this.SendPropertyChanging();
					this._SECU_ANSWER = value;
					this.SendPropertyChanged("SECU_ANSWER");
					this.OnSECU_ANSWERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="Int")]
		public System.Nullable<int> USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					if (this._TBL_USER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_USER_TBL_SECURITY", Storage="_TBL_USER", ThisKey="USER_ID", OtherKey="USER_ID", IsForeignKey=true)]
		public TBL_USER TBL_USER
		{
			get
			{
				return this._TBL_USER.Entity;
			}
			set
			{
				TBL_USER previousValue = this._TBL_USER.Entity;
				if (((previousValue != value) 
							|| (this._TBL_USER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_USER.Entity = null;
						previousValue.TBL_SECURITies.Remove(this);
					}
					this._TBL_USER.Entity = value;
					if ((value != null))
					{
						value.TBL_SECURITies.Add(this);
						this._USER_ID = value.USER_ID;
					}
					else
					{
						this._USER_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_USER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STUDENT")]
	public partial class TBL_STUDENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ST_ID;
		
		private string _ST_CURRENTID;
		
		private string _ST_FIRSTNAME;
		
		private string _ST_MIDDLENAME;
		
		private string _ST_LASTNAME;
		
		private string _ST_YEARLEVEL;
		
		private string _ST_SCHOOLYEAR;
		
		private System.DateTime _ST_BIRTHDATE;
		
		private int _ST_AGE;
		
		private string _ST_BIRTHPLACE;
		
		private string _ST_ADDRESS;
		
		private string _ST_GENDER;
		
		private string _ST_CONTACTNUMBER;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private double _ST_HEIGHT;
		
		private double _ST_WEIGHT;
		
		private string _ST_BLOODPRESSURE;
		
		private System.Nullable<int> _P_ID;
		
		private EntityRef<TBL_PARENT> _TBL_PARENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnST_IDChanging(int value);
    partial void OnST_IDChanged();
    partial void OnST_CURRENTIDChanging(string value);
    partial void OnST_CURRENTIDChanged();
    partial void OnST_FIRSTNAMEChanging(string value);
    partial void OnST_FIRSTNAMEChanged();
    partial void OnST_MIDDLENAMEChanging(string value);
    partial void OnST_MIDDLENAMEChanged();
    partial void OnST_LASTNAMEChanging(string value);
    partial void OnST_LASTNAMEChanged();
    partial void OnST_YEARLEVELChanging(string value);
    partial void OnST_YEARLEVELChanged();
    partial void OnST_SCHOOLYEARChanging(string value);
    partial void OnST_SCHOOLYEARChanged();
    partial void OnST_BIRTHDATEChanging(System.DateTime value);
    partial void OnST_BIRTHDATEChanged();
    partial void OnST_AGEChanging(int value);
    partial void OnST_AGEChanged();
    partial void OnST_BIRTHPLACEChanging(string value);
    partial void OnST_BIRTHPLACEChanged();
    partial void OnST_ADDRESSChanging(string value);
    partial void OnST_ADDRESSChanged();
    partial void OnST_GENDERChanging(string value);
    partial void OnST_GENDERChanged();
    partial void OnST_CONTACTNUMBERChanging(string value);
    partial void OnST_CONTACTNUMBERChanged();
    partial void OnISACTIVEChanging(System.Nullable<bool> value);
    partial void OnISACTIVEChanged();
    partial void OnST_HEIGHTChanging(double value);
    partial void OnST_HEIGHTChanged();
    partial void OnST_WEIGHTChanging(double value);
    partial void OnST_WEIGHTChanged();
    partial void OnST_BLOODPRESSUREChanging(string value);
    partial void OnST_BLOODPRESSUREChanged();
    partial void OnP_IDChanging(System.Nullable<int> value);
    partial void OnP_IDChanged();
    #endregion
		
		public TBL_STUDENT()
		{
			this._TBL_PARENT = default(EntityRef<TBL_PARENT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ST_ID
		{
			get
			{
				return this._ST_ID;
			}
			set
			{
				if ((this._ST_ID != value))
				{
					this.OnST_IDChanging(value);
					this.SendPropertyChanging();
					this._ST_ID = value;
					this.SendPropertyChanged("ST_ID");
					this.OnST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CURRENTID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ST_CURRENTID
		{
			get
			{
				return this._ST_CURRENTID;
			}
			set
			{
				if ((this._ST_CURRENTID != value))
				{
					this.OnST_CURRENTIDChanging(value);
					this.SendPropertyChanging();
					this._ST_CURRENTID = value;
					this.SendPropertyChanged("ST_CURRENTID");
					this.OnST_CURRENTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_FIRSTNAME
		{
			get
			{
				return this._ST_FIRSTNAME;
			}
			set
			{
				if ((this._ST_FIRSTNAME != value))
				{
					this.OnST_FIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._ST_FIRSTNAME = value;
					this.SendPropertyChanged("ST_FIRSTNAME");
					this.OnST_FIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_MIDDLENAME", DbType="VarChar(50)")]
		public string ST_MIDDLENAME
		{
			get
			{
				return this._ST_MIDDLENAME;
			}
			set
			{
				if ((this._ST_MIDDLENAME != value))
				{
					this.OnST_MIDDLENAMEChanging(value);
					this.SendPropertyChanging();
					this._ST_MIDDLENAME = value;
					this.SendPropertyChanged("ST_MIDDLENAME");
					this.OnST_MIDDLENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_LASTNAME
		{
			get
			{
				return this._ST_LASTNAME;
			}
			set
			{
				if ((this._ST_LASTNAME != value))
				{
					this.OnST_LASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._ST_LASTNAME = value;
					this.SendPropertyChanged("ST_LASTNAME");
					this.OnST_LASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_YEARLEVEL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_YEARLEVEL
		{
			get
			{
				return this._ST_YEARLEVEL;
			}
			set
			{
				if ((this._ST_YEARLEVEL != value))
				{
					this.OnST_YEARLEVELChanging(value);
					this.SendPropertyChanging();
					this._ST_YEARLEVEL = value;
					this.SendPropertyChanged("ST_YEARLEVEL");
					this.OnST_YEARLEVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_SCHOOLYEAR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_SCHOOLYEAR
		{
			get
			{
				return this._ST_SCHOOLYEAR;
			}
			set
			{
				if ((this._ST_SCHOOLYEAR != value))
				{
					this.OnST_SCHOOLYEARChanging(value);
					this.SendPropertyChanging();
					this._ST_SCHOOLYEAR = value;
					this.SendPropertyChanged("ST_SCHOOLYEAR");
					this.OnST_SCHOOLYEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHDATE", DbType="Date NOT NULL")]
		public System.DateTime ST_BIRTHDATE
		{
			get
			{
				return this._ST_BIRTHDATE;
			}
			set
			{
				if ((this._ST_BIRTHDATE != value))
				{
					this.OnST_BIRTHDATEChanging(value);
					this.SendPropertyChanging();
					this._ST_BIRTHDATE = value;
					this.SendPropertyChanged("ST_BIRTHDATE");
					this.OnST_BIRTHDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_AGE", DbType="Int NOT NULL")]
		public int ST_AGE
		{
			get
			{
				return this._ST_AGE;
			}
			set
			{
				if ((this._ST_AGE != value))
				{
					this.OnST_AGEChanging(value);
					this.SendPropertyChanging();
					this._ST_AGE = value;
					this.SendPropertyChanged("ST_AGE");
					this.OnST_AGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHPLACE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BIRTHPLACE
		{
			get
			{
				return this._ST_BIRTHPLACE;
			}
			set
			{
				if ((this._ST_BIRTHPLACE != value))
				{
					this.OnST_BIRTHPLACEChanging(value);
					this.SendPropertyChanging();
					this._ST_BIRTHPLACE = value;
					this.SendPropertyChanged("ST_BIRTHPLACE");
					this.OnST_BIRTHPLACEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ADDRESS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_ADDRESS
		{
			get
			{
				return this._ST_ADDRESS;
			}
			set
			{
				if ((this._ST_ADDRESS != value))
				{
					this.OnST_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ST_ADDRESS = value;
					this.SendPropertyChanged("ST_ADDRESS");
					this.OnST_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_GENDER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_GENDER
		{
			get
			{
				return this._ST_GENDER;
			}
			set
			{
				if ((this._ST_GENDER != value))
				{
					this.OnST_GENDERChanging(value);
					this.SendPropertyChanging();
					this._ST_GENDER = value;
					this.SendPropertyChanged("ST_GENDER");
					this.OnST_GENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CONTACTNUMBER", DbType="VarChar(50)")]
		public string ST_CONTACTNUMBER
		{
			get
			{
				return this._ST_CONTACTNUMBER;
			}
			set
			{
				if ((this._ST_CONTACTNUMBER != value))
				{
					this.OnST_CONTACTNUMBERChanging(value);
					this.SendPropertyChanging();
					this._ST_CONTACTNUMBER = value;
					this.SendPropertyChanged("ST_CONTACTNUMBER");
					this.OnST_CONTACTNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this.OnISACTIVEChanging(value);
					this.SendPropertyChanging();
					this._ISACTIVE = value;
					this.SendPropertyChanged("ISACTIVE");
					this.OnISACTIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_HEIGHT", DbType="Float NOT NULL")]
		public double ST_HEIGHT
		{
			get
			{
				return this._ST_HEIGHT;
			}
			set
			{
				if ((this._ST_HEIGHT != value))
				{
					this.OnST_HEIGHTChanging(value);
					this.SendPropertyChanging();
					this._ST_HEIGHT = value;
					this.SendPropertyChanged("ST_HEIGHT");
					this.OnST_HEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_WEIGHT", DbType="Float NOT NULL")]
		public double ST_WEIGHT
		{
			get
			{
				return this._ST_WEIGHT;
			}
			set
			{
				if ((this._ST_WEIGHT != value))
				{
					this.OnST_WEIGHTChanging(value);
					this.SendPropertyChanging();
					this._ST_WEIGHT = value;
					this.SendPropertyChanged("ST_WEIGHT");
					this.OnST_WEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BLOODPRESSURE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BLOODPRESSURE
		{
			get
			{
				return this._ST_BLOODPRESSURE;
			}
			set
			{
				if ((this._ST_BLOODPRESSURE != value))
				{
					this.OnST_BLOODPRESSUREChanging(value);
					this.SendPropertyChanging();
					this._ST_BLOODPRESSURE = value;
					this.SendPropertyChanged("ST_BLOODPRESSURE");
					this.OnST_BLOODPRESSUREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int")]
		public System.Nullable<int> P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					if (this._TBL_PARENT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_PARENT_TBL_STUDENT", Storage="_TBL_PARENT", ThisKey="P_ID", OtherKey="P_ID", IsForeignKey=true)]
		public TBL_PARENT TBL_PARENT
		{
			get
			{
				return this._TBL_PARENT.Entity;
			}
			set
			{
				TBL_PARENT previousValue = this._TBL_PARENT.Entity;
				if (((previousValue != value) 
							|| (this._TBL_PARENT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_PARENT.Entity = null;
						previousValue.TBL_STUDENTs.Remove(this);
					}
					this._TBL_PARENT.Entity = value;
					if ((value != null))
					{
						value.TBL_STUDENTs.Add(this);
						this._P_ID = value.P_ID;
					}
					else
					{
						this._P_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_PARENT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USERS")]
	public partial class TBL_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USER_ID;
		
		private string _USER_LASTNAME;
		
		private string _USER_FIRSTNAME;
		
		private string _USER_MIDDLENAME;
		
		private string _USER_USERNAME;
		
		private string _USER_PASSWORD;
		
		private string _USER_CONTACT;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private System.Nullable<System.DateTime> _USER_DATEADDED;
		
		private string _USER_CREATOR;
		
		private System.Nullable<int> _USER_TYPEID;
		
		private string _USER_IMAGE;
		
		private EntitySet<TBL_SECURITY> _TBL_SECURITies;
		
		private EntityRef<TBL_USERTYPE> _TBL_USERTYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSER_IDChanging(int value);
    partial void OnUSER_IDChanged();
    partial void OnUSER_LASTNAMEChanging(string value);
    partial void OnUSER_LASTNAMEChanged();
    partial void OnUSER_FIRSTNAMEChanging(string value);
    partial void OnUSER_FIRSTNAMEChanged();
    partial void OnUSER_MIDDLENAMEChanging(string value);
    partial void OnUSER_MIDDLENAMEChanged();
    partial void OnUSER_USERNAMEChanging(string value);
    partial void OnUSER_USERNAMEChanged();
    partial void OnUSER_PASSWORDChanging(string value);
    partial void OnUSER_PASSWORDChanged();
    partial void OnUSER_CONTACTChanging(string value);
    partial void OnUSER_CONTACTChanged();
    partial void OnISACTIVEChanging(System.Nullable<bool> value);
    partial void OnISACTIVEChanged();
    partial void OnUSER_DATEADDEDChanging(System.Nullable<System.DateTime> value);
    partial void OnUSER_DATEADDEDChanged();
    partial void OnUSER_CREATORChanging(string value);
    partial void OnUSER_CREATORChanged();
    partial void OnUSER_TYPEIDChanging(System.Nullable<int> value);
    partial void OnUSER_TYPEIDChanged();
    partial void OnUSER_IMAGEChanging(string value);
    partial void OnUSER_IMAGEChanged();
    #endregion
		
		public TBL_USER()
		{
			this._TBL_SECURITies = new EntitySet<TBL_SECURITY>(new Action<TBL_SECURITY>(this.attach_TBL_SECURITies), new Action<TBL_SECURITY>(this.detach_TBL_SECURITies));
			this._TBL_USERTYPE = default(EntityRef<TBL_USERTYPE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_LASTNAME
		{
			get
			{
				return this._USER_LASTNAME;
			}
			set
			{
				if ((this._USER_LASTNAME != value))
				{
					this.OnUSER_LASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_LASTNAME = value;
					this.SendPropertyChanged("USER_LASTNAME");
					this.OnUSER_LASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_FIRSTNAME
		{
			get
			{
				return this._USER_FIRSTNAME;
			}
			set
			{
				if ((this._USER_FIRSTNAME != value))
				{
					this.OnUSER_FIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_FIRSTNAME = value;
					this.SendPropertyChanged("USER_FIRSTNAME");
					this.OnUSER_FIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_MIDDLENAME", DbType="VarChar(50)")]
		public string USER_MIDDLENAME
		{
			get
			{
				return this._USER_MIDDLENAME;
			}
			set
			{
				if ((this._USER_MIDDLENAME != value))
				{
					this.OnUSER_MIDDLENAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_MIDDLENAME = value;
					this.SendPropertyChanged("USER_MIDDLENAME");
					this.OnUSER_MIDDLENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_USERNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_USERNAME
		{
			get
			{
				return this._USER_USERNAME;
			}
			set
			{
				if ((this._USER_USERNAME != value))
				{
					this.OnUSER_USERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_USERNAME = value;
					this.SendPropertyChanged("USER_USERNAME");
					this.OnUSER_USERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_PASSWORD
		{
			get
			{
				return this._USER_PASSWORD;
			}
			set
			{
				if ((this._USER_PASSWORD != value))
				{
					this.OnUSER_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._USER_PASSWORD = value;
					this.SendPropertyChanged("USER_PASSWORD");
					this.OnUSER_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_CONTACT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_CONTACT
		{
			get
			{
				return this._USER_CONTACT;
			}
			set
			{
				if ((this._USER_CONTACT != value))
				{
					this.OnUSER_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._USER_CONTACT = value;
					this.SendPropertyChanged("USER_CONTACT");
					this.OnUSER_CONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this.OnISACTIVEChanging(value);
					this.SendPropertyChanging();
					this._ISACTIVE = value;
					this.SendPropertyChanged("ISACTIVE");
					this.OnISACTIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_DATEADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> USER_DATEADDED
		{
			get
			{
				return this._USER_DATEADDED;
			}
			set
			{
				if ((this._USER_DATEADDED != value))
				{
					this.OnUSER_DATEADDEDChanging(value);
					this.SendPropertyChanging();
					this._USER_DATEADDED = value;
					this.SendPropertyChanged("USER_DATEADDED");
					this.OnUSER_DATEADDEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_CREATOR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_CREATOR
		{
			get
			{
				return this._USER_CREATOR;
			}
			set
			{
				if ((this._USER_CREATOR != value))
				{
					this.OnUSER_CREATORChanging(value);
					this.SendPropertyChanging();
					this._USER_CREATOR = value;
					this.SendPropertyChanged("USER_CREATOR");
					this.OnUSER_CREATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPEID", DbType="Int")]
		public System.Nullable<int> USER_TYPEID
		{
			get
			{
				return this._USER_TYPEID;
			}
			set
			{
				if ((this._USER_TYPEID != value))
				{
					if (this._TBL_USERTYPE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSER_TYPEIDChanging(value);
					this.SendPropertyChanging();
					this._USER_TYPEID = value;
					this.SendPropertyChanged("USER_TYPEID");
					this.OnUSER_TYPEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_IMAGE", DbType="VarChar(MAX)")]
		public string USER_IMAGE
		{
			get
			{
				return this._USER_IMAGE;
			}
			set
			{
				if ((this._USER_IMAGE != value))
				{
					this.OnUSER_IMAGEChanging(value);
					this.SendPropertyChanging();
					this._USER_IMAGE = value;
					this.SendPropertyChanged("USER_IMAGE");
					this.OnUSER_IMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_USER_TBL_SECURITY", Storage="_TBL_SECURITies", ThisKey="USER_ID", OtherKey="USER_ID")]
		public EntitySet<TBL_SECURITY> TBL_SECURITies
		{
			get
			{
				return this._TBL_SECURITies;
			}
			set
			{
				this._TBL_SECURITies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_USERTYPE_TBL_USER", Storage="_TBL_USERTYPE", ThisKey="USER_TYPEID", OtherKey="USER_TYPEID", IsForeignKey=true)]
		public TBL_USERTYPE TBL_USERTYPE
		{
			get
			{
				return this._TBL_USERTYPE.Entity;
			}
			set
			{
				TBL_USERTYPE previousValue = this._TBL_USERTYPE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_USERTYPE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_USERTYPE.Entity = null;
						previousValue.TBL_USERs.Remove(this);
					}
					this._TBL_USERTYPE.Entity = value;
					if ((value != null))
					{
						value.TBL_USERs.Add(this);
						this._USER_TYPEID = value.USER_TYPEID;
					}
					else
					{
						this._USER_TYPEID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TBL_USERTYPE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_SECURITies(TBL_SECURITY entity)
		{
			this.SendPropertyChanging();
			entity.TBL_USER = this;
		}
		
		private void detach_TBL_SECURITies(TBL_SECURITY entity)
		{
			this.SendPropertyChanging();
			entity.TBL_USER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_STANDPT")]
	public partial class View_STANDPT
	{
		
		private int _ST_ID;
		
		private string _ST_CURRENTID;
		
		private string _ST_FIRSTNAME;
		
		private string _ST_MIDDLENAME;
		
		private string _ST_LASTNAME;
		
		private string _ST_YEARLEVEL;
		
		private string _ST_SCHOOLYEAR;
		
		private System.DateTime _ST_BIRTHDATE;
		
		private int _ST_AGE;
		
		private string _ST_BIRTHPLACE;
		
		private string _ST_ADDRESS;
		
		private string _ST_GENDER;
		
		private string _ST_CONTACTNUMBER;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private double _ST_HEIGHT;
		
		private double _ST_WEIGHT;
		
		private string _ST_BLOODPRESSURE;
		
		private int _P_ID;
		
		private string _P_NAME;
		
		private string _P_CONTACT;
		
		private string _P_OCCUPATION;
		
		public View_STANDPT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ID", DbType="Int NOT NULL")]
		public int ST_ID
		{
			get
			{
				return this._ST_ID;
			}
			set
			{
				if ((this._ST_ID != value))
				{
					this._ST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CURRENTID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_CURRENTID
		{
			get
			{
				return this._ST_CURRENTID;
			}
			set
			{
				if ((this._ST_CURRENTID != value))
				{
					this._ST_CURRENTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_FIRSTNAME
		{
			get
			{
				return this._ST_FIRSTNAME;
			}
			set
			{
				if ((this._ST_FIRSTNAME != value))
				{
					this._ST_FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_MIDDLENAME", DbType="VarChar(50)")]
		public string ST_MIDDLENAME
		{
			get
			{
				return this._ST_MIDDLENAME;
			}
			set
			{
				if ((this._ST_MIDDLENAME != value))
				{
					this._ST_MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_LASTNAME
		{
			get
			{
				return this._ST_LASTNAME;
			}
			set
			{
				if ((this._ST_LASTNAME != value))
				{
					this._ST_LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_YEARLEVEL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_YEARLEVEL
		{
			get
			{
				return this._ST_YEARLEVEL;
			}
			set
			{
				if ((this._ST_YEARLEVEL != value))
				{
					this._ST_YEARLEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_SCHOOLYEAR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_SCHOOLYEAR
		{
			get
			{
				return this._ST_SCHOOLYEAR;
			}
			set
			{
				if ((this._ST_SCHOOLYEAR != value))
				{
					this._ST_SCHOOLYEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHDATE", DbType="Date NOT NULL")]
		public System.DateTime ST_BIRTHDATE
		{
			get
			{
				return this._ST_BIRTHDATE;
			}
			set
			{
				if ((this._ST_BIRTHDATE != value))
				{
					this._ST_BIRTHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_AGE", DbType="Int NOT NULL")]
		public int ST_AGE
		{
			get
			{
				return this._ST_AGE;
			}
			set
			{
				if ((this._ST_AGE != value))
				{
					this._ST_AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHPLACE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BIRTHPLACE
		{
			get
			{
				return this._ST_BIRTHPLACE;
			}
			set
			{
				if ((this._ST_BIRTHPLACE != value))
				{
					this._ST_BIRTHPLACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ADDRESS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_ADDRESS
		{
			get
			{
				return this._ST_ADDRESS;
			}
			set
			{
				if ((this._ST_ADDRESS != value))
				{
					this._ST_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_GENDER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_GENDER
		{
			get
			{
				return this._ST_GENDER;
			}
			set
			{
				if ((this._ST_GENDER != value))
				{
					this._ST_GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CONTACTNUMBER", DbType="VarChar(50)")]
		public string ST_CONTACTNUMBER
		{
			get
			{
				return this._ST_CONTACTNUMBER;
			}
			set
			{
				if ((this._ST_CONTACTNUMBER != value))
				{
					this._ST_CONTACTNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this._ISACTIVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_HEIGHT", DbType="Float NOT NULL")]
		public double ST_HEIGHT
		{
			get
			{
				return this._ST_HEIGHT;
			}
			set
			{
				if ((this._ST_HEIGHT != value))
				{
					this._ST_HEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_WEIGHT", DbType="Float NOT NULL")]
		public double ST_WEIGHT
		{
			get
			{
				return this._ST_WEIGHT;
			}
			set
			{
				if ((this._ST_WEIGHT != value))
				{
					this._ST_WEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BLOODPRESSURE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BLOODPRESSURE
		{
			get
			{
				return this._ST_BLOODPRESSURE;
			}
			set
			{
				if ((this._ST_BLOODPRESSURE != value))
				{
					this._ST_BLOODPRESSURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int NOT NULL")]
		public int P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this._P_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_NAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_NAME
		{
			get
			{
				return this._P_NAME;
			}
			set
			{
				if ((this._P_NAME != value))
				{
					this._P_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_CONTACT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_CONTACT
		{
			get
			{
				return this._P_CONTACT;
			}
			set
			{
				if ((this._P_CONTACT != value))
				{
					this._P_CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_OCCUPATION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_OCCUPATION
		{
			get
			{
				return this._P_OCCUPATION;
			}
			set
			{
				if ((this._P_OCCUPATION != value))
				{
					this._P_OCCUPATION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_User")]
	public partial class View_User
	{
		
		private int _USER_ID;
		
		private string _USER_LASTNAME;
		
		private string _USER_FIRSTNAME;
		
		private string _USER_MIDDLENAME;
		
		private string _USER_USERNAME;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private System.Nullable<int> _USER_TYPEID;
		
		private string _USER_IMAGE;
		
		public View_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_LASTNAME
		{
			get
			{
				return this._USER_LASTNAME;
			}
			set
			{
				if ((this._USER_LASTNAME != value))
				{
					this._USER_LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_FIRSTNAME
		{
			get
			{
				return this._USER_FIRSTNAME;
			}
			set
			{
				if ((this._USER_FIRSTNAME != value))
				{
					this._USER_FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_MIDDLENAME", DbType="VarChar(50)")]
		public string USER_MIDDLENAME
		{
			get
			{
				return this._USER_MIDDLENAME;
			}
			set
			{
				if ((this._USER_MIDDLENAME != value))
				{
					this._USER_MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_USERNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_USERNAME
		{
			get
			{
				return this._USER_USERNAME;
			}
			set
			{
				if ((this._USER_USERNAME != value))
				{
					this._USER_USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this._ISACTIVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPEID", DbType="Int")]
		public System.Nullable<int> USER_TYPEID
		{
			get
			{
				return this._USER_TYPEID;
			}
			set
			{
				if ((this._USER_TYPEID != value))
				{
					this._USER_TYPEID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_IMAGE", DbType="VarChar(MAX)")]
		public string USER_IMAGE
		{
			get
			{
				return this._USER_IMAGE;
			}
			set
			{
				if ((this._USER_IMAGE != value))
				{
					this._USER_IMAGE = value;
				}
			}
		}
	}
	
	public partial class SP_ACCOUNTRECOVERYResult
	{
		
		private string _USER_USERNAME;
		
		private string _SECU_QUESTION;
		
		private string _SECU_ANSWER;
		
		public SP_ACCOUNTRECOVERYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_USERNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_USERNAME
		{
			get
			{
				return this._USER_USERNAME;
			}
			set
			{
				if ((this._USER_USERNAME != value))
				{
					this._USER_USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECU_QUESTION", DbType="VarChar(50)")]
		public string SECU_QUESTION
		{
			get
			{
				return this._SECU_QUESTION;
			}
			set
			{
				if ((this._SECU_QUESTION != value))
				{
					this._SECU_QUESTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECU_ANSWER", DbType="VarChar(50)")]
		public string SECU_ANSWER
		{
			get
			{
				return this._SECU_ANSWER;
			}
			set
			{
				if ((this._SECU_ANSWER != value))
				{
					this._SECU_ANSWER = value;
				}
			}
		}
	}
	
	public partial class SP_STSEARCHResult
	{
		
		private int _ST_ID;
		
		private string _ST_CURRENTID;
		
		private string _ST_FIRSTNAME;
		
		private string _ST_MIDDLENAME;
		
		private string _ST_LASTNAME;
		
		private string _ST_YEARLEVEL;
		
		private string _ST_SCHOOLYEAR;
		
		private System.DateTime _ST_BIRTHDATE;
		
		private int _ST_AGE;
		
		private string _ST_BIRTHPLACE;
		
		private string _ST_ADDRESS;
		
		private string _ST_GENDER;
		
		private string _ST_CONTACTNUMBER;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private double _ST_HEIGHT;
		
		private double _ST_WEIGHT;
		
		private string _ST_BLOODPRESSURE;
		
		private System.Nullable<int> _P_ID;
		
		public SP_STSEARCHResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ID", DbType="Int NOT NULL")]
		public int ST_ID
		{
			get
			{
				return this._ST_ID;
			}
			set
			{
				if ((this._ST_ID != value))
				{
					this._ST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CURRENTID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_CURRENTID
		{
			get
			{
				return this._ST_CURRENTID;
			}
			set
			{
				if ((this._ST_CURRENTID != value))
				{
					this._ST_CURRENTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_FIRSTNAME
		{
			get
			{
				return this._ST_FIRSTNAME;
			}
			set
			{
				if ((this._ST_FIRSTNAME != value))
				{
					this._ST_FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_MIDDLENAME", DbType="VarChar(50)")]
		public string ST_MIDDLENAME
		{
			get
			{
				return this._ST_MIDDLENAME;
			}
			set
			{
				if ((this._ST_MIDDLENAME != value))
				{
					this._ST_MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_LASTNAME
		{
			get
			{
				return this._ST_LASTNAME;
			}
			set
			{
				if ((this._ST_LASTNAME != value))
				{
					this._ST_LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_YEARLEVEL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_YEARLEVEL
		{
			get
			{
				return this._ST_YEARLEVEL;
			}
			set
			{
				if ((this._ST_YEARLEVEL != value))
				{
					this._ST_YEARLEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_SCHOOLYEAR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_SCHOOLYEAR
		{
			get
			{
				return this._ST_SCHOOLYEAR;
			}
			set
			{
				if ((this._ST_SCHOOLYEAR != value))
				{
					this._ST_SCHOOLYEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHDATE", DbType="Date NOT NULL")]
		public System.DateTime ST_BIRTHDATE
		{
			get
			{
				return this._ST_BIRTHDATE;
			}
			set
			{
				if ((this._ST_BIRTHDATE != value))
				{
					this._ST_BIRTHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_AGE", DbType="Int NOT NULL")]
		public int ST_AGE
		{
			get
			{
				return this._ST_AGE;
			}
			set
			{
				if ((this._ST_AGE != value))
				{
					this._ST_AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHPLACE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BIRTHPLACE
		{
			get
			{
				return this._ST_BIRTHPLACE;
			}
			set
			{
				if ((this._ST_BIRTHPLACE != value))
				{
					this._ST_BIRTHPLACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ADDRESS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_ADDRESS
		{
			get
			{
				return this._ST_ADDRESS;
			}
			set
			{
				if ((this._ST_ADDRESS != value))
				{
					this._ST_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_GENDER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_GENDER
		{
			get
			{
				return this._ST_GENDER;
			}
			set
			{
				if ((this._ST_GENDER != value))
				{
					this._ST_GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CONTACTNUMBER", DbType="VarChar(50)")]
		public string ST_CONTACTNUMBER
		{
			get
			{
				return this._ST_CONTACTNUMBER;
			}
			set
			{
				if ((this._ST_CONTACTNUMBER != value))
				{
					this._ST_CONTACTNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this._ISACTIVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_HEIGHT", DbType="Float NOT NULL")]
		public double ST_HEIGHT
		{
			get
			{
				return this._ST_HEIGHT;
			}
			set
			{
				if ((this._ST_HEIGHT != value))
				{
					this._ST_HEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_WEIGHT", DbType="Float NOT NULL")]
		public double ST_WEIGHT
		{
			get
			{
				return this._ST_WEIGHT;
			}
			set
			{
				if ((this._ST_WEIGHT != value))
				{
					this._ST_WEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BLOODPRESSURE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BLOODPRESSURE
		{
			get
			{
				return this._ST_BLOODPRESSURE;
			}
			set
			{
				if ((this._ST_BLOODPRESSURE != value))
				{
					this._ST_BLOODPRESSURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int")]
		public System.Nullable<int> P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this._P_ID = value;
				}
			}
		}
	}
	
	public partial class SP_STVIEWResult
	{
		
		private int _ST_ID;
		
		private string _ST_CURRENTID;
		
		private string _ST_FIRSTNAME;
		
		private string _ST_MIDDLENAME;
		
		private string _ST_LASTNAME;
		
		private string _ST_YEARLEVEL;
		
		private string _ST_SCHOOLYEAR;
		
		private System.DateTime _ST_BIRTHDATE;
		
		private int _ST_AGE;
		
		private string _ST_BIRTHPLACE;
		
		private string _ST_ADDRESS;
		
		private string _ST_GENDER;
		
		private string _ST_CONTACTNUMBER;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private double _ST_HEIGHT;
		
		private double _ST_WEIGHT;
		
		private string _ST_BLOODPRESSURE;
		
		private System.Nullable<int> _P_ID;
		
		public SP_STVIEWResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ID", DbType="Int NOT NULL")]
		public int ST_ID
		{
			get
			{
				return this._ST_ID;
			}
			set
			{
				if ((this._ST_ID != value))
				{
					this._ST_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CURRENTID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_CURRENTID
		{
			get
			{
				return this._ST_CURRENTID;
			}
			set
			{
				if ((this._ST_CURRENTID != value))
				{
					this._ST_CURRENTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_FIRSTNAME
		{
			get
			{
				return this._ST_FIRSTNAME;
			}
			set
			{
				if ((this._ST_FIRSTNAME != value))
				{
					this._ST_FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_MIDDLENAME", DbType="VarChar(50)")]
		public string ST_MIDDLENAME
		{
			get
			{
				return this._ST_MIDDLENAME;
			}
			set
			{
				if ((this._ST_MIDDLENAME != value))
				{
					this._ST_MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_LASTNAME
		{
			get
			{
				return this._ST_LASTNAME;
			}
			set
			{
				if ((this._ST_LASTNAME != value))
				{
					this._ST_LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_YEARLEVEL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_YEARLEVEL
		{
			get
			{
				return this._ST_YEARLEVEL;
			}
			set
			{
				if ((this._ST_YEARLEVEL != value))
				{
					this._ST_YEARLEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_SCHOOLYEAR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_SCHOOLYEAR
		{
			get
			{
				return this._ST_SCHOOLYEAR;
			}
			set
			{
				if ((this._ST_SCHOOLYEAR != value))
				{
					this._ST_SCHOOLYEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHDATE", DbType="Date NOT NULL")]
		public System.DateTime ST_BIRTHDATE
		{
			get
			{
				return this._ST_BIRTHDATE;
			}
			set
			{
				if ((this._ST_BIRTHDATE != value))
				{
					this._ST_BIRTHDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_AGE", DbType="Int NOT NULL")]
		public int ST_AGE
		{
			get
			{
				return this._ST_AGE;
			}
			set
			{
				if ((this._ST_AGE != value))
				{
					this._ST_AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BIRTHPLACE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BIRTHPLACE
		{
			get
			{
				return this._ST_BIRTHPLACE;
			}
			set
			{
				if ((this._ST_BIRTHPLACE != value))
				{
					this._ST_BIRTHPLACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ADDRESS", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_ADDRESS
		{
			get
			{
				return this._ST_ADDRESS;
			}
			set
			{
				if ((this._ST_ADDRESS != value))
				{
					this._ST_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_GENDER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_GENDER
		{
			get
			{
				return this._ST_GENDER;
			}
			set
			{
				if ((this._ST_GENDER != value))
				{
					this._ST_GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_CONTACTNUMBER", DbType="VarChar(50)")]
		public string ST_CONTACTNUMBER
		{
			get
			{
				return this._ST_CONTACTNUMBER;
			}
			set
			{
				if ((this._ST_CONTACTNUMBER != value))
				{
					this._ST_CONTACTNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this._ISACTIVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_HEIGHT", DbType="Float NOT NULL")]
		public double ST_HEIGHT
		{
			get
			{
				return this._ST_HEIGHT;
			}
			set
			{
				if ((this._ST_HEIGHT != value))
				{
					this._ST_HEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_WEIGHT", DbType="Float NOT NULL")]
		public double ST_WEIGHT
		{
			get
			{
				return this._ST_WEIGHT;
			}
			set
			{
				if ((this._ST_WEIGHT != value))
				{
					this._ST_WEIGHT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_BLOODPRESSURE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ST_BLOODPRESSURE
		{
			get
			{
				return this._ST_BLOODPRESSURE;
			}
			set
			{
				if ((this._ST_BLOODPRESSURE != value))
				{
					this._ST_BLOODPRESSURE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", DbType="Int")]
		public System.Nullable<int> P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this._P_ID = value;
				}
			}
		}
	}
	
	public partial class SP_USERSEARCHResult
	{
		
		private int _USER_ID;
		
		private string _USER_LASTNAME;
		
		private string _USER_FIRSTNAME;
		
		private string _USER_MIDDLENAME;
		
		private string _USER_USERNAME;
		
		private string _USER_PASSWORD;
		
		private string _USER_CONTACT;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private System.Nullable<System.DateTime> _USER_DATEADDED;
		
		private string _USER_CREATOR;
		
		private System.Nullable<int> _USER_TYPEID;
		
		private string _USER_IMAGE;
		
		public SP_USERSEARCHResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="Int NOT NULL")]
		public int USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_LASTNAME
		{
			get
			{
				return this._USER_LASTNAME;
			}
			set
			{
				if ((this._USER_LASTNAME != value))
				{
					this._USER_LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_FIRSTNAME
		{
			get
			{
				return this._USER_FIRSTNAME;
			}
			set
			{
				if ((this._USER_FIRSTNAME != value))
				{
					this._USER_FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_MIDDLENAME", DbType="VarChar(50)")]
		public string USER_MIDDLENAME
		{
			get
			{
				return this._USER_MIDDLENAME;
			}
			set
			{
				if ((this._USER_MIDDLENAME != value))
				{
					this._USER_MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_USERNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_USERNAME
		{
			get
			{
				return this._USER_USERNAME;
			}
			set
			{
				if ((this._USER_USERNAME != value))
				{
					this._USER_USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_PASSWORD
		{
			get
			{
				return this._USER_PASSWORD;
			}
			set
			{
				if ((this._USER_PASSWORD != value))
				{
					this._USER_PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_CONTACT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_CONTACT
		{
			get
			{
				return this._USER_CONTACT;
			}
			set
			{
				if ((this._USER_CONTACT != value))
				{
					this._USER_CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this._ISACTIVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_DATEADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> USER_DATEADDED
		{
			get
			{
				return this._USER_DATEADDED;
			}
			set
			{
				if ((this._USER_DATEADDED != value))
				{
					this._USER_DATEADDED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_CREATOR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_CREATOR
		{
			get
			{
				return this._USER_CREATOR;
			}
			set
			{
				if ((this._USER_CREATOR != value))
				{
					this._USER_CREATOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPEID", DbType="Int")]
		public System.Nullable<int> USER_TYPEID
		{
			get
			{
				return this._USER_TYPEID;
			}
			set
			{
				if ((this._USER_TYPEID != value))
				{
					this._USER_TYPEID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_IMAGE", DbType="VarChar(MAX)")]
		public string USER_IMAGE
		{
			get
			{
				return this._USER_IMAGE;
			}
			set
			{
				if ((this._USER_IMAGE != value))
				{
					this._USER_IMAGE = value;
				}
			}
		}
	}
	
	public partial class SP_USERVIEWResult
	{
		
		private int _USER_ID;
		
		private string _USER_LASTNAME;
		
		private string _USER_FIRSTNAME;
		
		private string _USER_MIDDLENAME;
		
		private string _USER_USERNAME;
		
		private string _USER_PASSWORD;
		
		private string _USER_CONTACT;
		
		private System.Nullable<bool> _ISACTIVE;
		
		private System.Nullable<System.DateTime> _USER_DATEADDED;
		
		private string _USER_CREATOR;
		
		private System.Nullable<int> _USER_TYPEID;
		
		private string _USER_IMAGE;
		
		public SP_USERVIEWResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="Int NOT NULL")]
		public int USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_LASTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_LASTNAME
		{
			get
			{
				return this._USER_LASTNAME;
			}
			set
			{
				if ((this._USER_LASTNAME != value))
				{
					this._USER_LASTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_FIRSTNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_FIRSTNAME
		{
			get
			{
				return this._USER_FIRSTNAME;
			}
			set
			{
				if ((this._USER_FIRSTNAME != value))
				{
					this._USER_FIRSTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_MIDDLENAME", DbType="VarChar(50)")]
		public string USER_MIDDLENAME
		{
			get
			{
				return this._USER_MIDDLENAME;
			}
			set
			{
				if ((this._USER_MIDDLENAME != value))
				{
					this._USER_MIDDLENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_USERNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_USERNAME
		{
			get
			{
				return this._USER_USERNAME;
			}
			set
			{
				if ((this._USER_USERNAME != value))
				{
					this._USER_USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_PASSWORD
		{
			get
			{
				return this._USER_PASSWORD;
			}
			set
			{
				if ((this._USER_PASSWORD != value))
				{
					this._USER_PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_CONTACT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_CONTACT
		{
			get
			{
				return this._USER_CONTACT;
			}
			set
			{
				if ((this._USER_CONTACT != value))
				{
					this._USER_CONTACT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this._ISACTIVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_DATEADDED", DbType="DateTime")]
		public System.Nullable<System.DateTime> USER_DATEADDED
		{
			get
			{
				return this._USER_DATEADDED;
			}
			set
			{
				if ((this._USER_DATEADDED != value))
				{
					this._USER_DATEADDED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_CREATOR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_CREATOR
		{
			get
			{
				return this._USER_CREATOR;
			}
			set
			{
				if ((this._USER_CREATOR != value))
				{
					this._USER_CREATOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_TYPEID", DbType="Int")]
		public System.Nullable<int> USER_TYPEID
		{
			get
			{
				return this._USER_TYPEID;
			}
			set
			{
				if ((this._USER_TYPEID != value))
				{
					this._USER_TYPEID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_IMAGE", DbType="VarChar(MAX)")]
		public string USER_IMAGE
		{
			get
			{
				return this._USER_IMAGE;
			}
			set
			{
				if ((this._USER_IMAGE != value))
				{
					this._USER_IMAGE = value;
				}
			}
		}
	}
	
	public partial class SP_VERIFYPASSWORDResult
	{
		
		private string _USER_PASSWORD;
		
		public SP_VERIFYPASSWORDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_PASSWORD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string USER_PASSWORD
		{
			get
			{
				return this._USER_PASSWORD;
			}
			set
			{
				if ((this._USER_PASSWORD != value))
				{
					this._USER_PASSWORD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
