<?xml version="1.0" encoding="utf-8"?><Database Name="ANS_DATABASE" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ANS_DATABASE;Integrated Security=True" SettingsObjectName="ABELLANA_NATIONAL_SCHOOL_FINAL.Properties.Settings" SettingsPropertyName="ANS_DATABASEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_BMICOMP" Member="TBL_BMICOMPs">
    <Type Name="TBL_BMICOMP">
      <Column Name="BMI_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BMI_HWRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BMI_BPRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_STUDENT_TBL_BMICOMP" Member="TBL_STUDENT" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USERTYPE" Member="TBL_USERTYPEs">
    <Type Name="TBL_USERTYPE">
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_TYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_USERTYPE_TBL_USER" Member="TBL_USERs" ThisKey="USER_TYPEID" OtherKey="USER_TYPEID" Type="TBL_USER" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BOOKS" Member="TBL_BOOKs">
    <Type Name="TBL_BOOK">
      <Column Name="B_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="B_BOOKNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKDESC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B_AUTHOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B_PUBLISHED" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="TBL_BOOK_TBL_STUDBOOK" Member="TBL_STUDBOOKs" ThisKey="B_ID" OtherKey="B_ID" Type="TBL_STUDBOOK" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_GRADE" Member="TBL_GRADEs">
    <Type Name="TBL_GRADE">
      <Column Name="GRADE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GRADEPERIOD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GRADE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUBJECT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_STUDENT_TBL_GRADE" Member="TBL_STUDENT" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDENT" IsForeignKey="true" />
      <Association Name="TBL_SUBJECT_TBL_GRADE" Member="TBL_SUBJECT" ThisKey="SUBJECT_ID" OtherKey="SUBJECT_ID" Type="TBL_SUBJECT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PARENT" Member="TBL_PARENTs">
    <Type Name="TBL_PARENT">
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="P_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_OCCUPATION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TBL_PARENT_TBL_STUDENT" Member="TBL_STUDENTs" ThisKey="P_ID" OtherKey="P_ID" Type="TBL_STUDENT" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PAYMENT" Member="TBL_PAYMENTs">
    <Type Name="TBL_PAYMENT">
      <Column Name="PAYMENT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PAYMENT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_PAYMENT_TBL_PAYMENTDETAIL" Member="TBL_PAYMENTDETAILs" ThisKey="PAYMENT_ID" OtherKey="PAYMENT_ID" Type="TBL_PAYMENTDETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PAYMENTDETAILS" Member="TBL_PAYMENTDETAILs">
    <Type Name="TBL_PAYMENTDETAIL">
      <Column Name="PD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PAYMENTFOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTAMOUNT" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_PAYMENTDETAIL_TBL_STANDPAY" Member="TBL_STANDPAYs" ThisKey="PD_ID" OtherKey="PD_ID" Type="TBL_STANDPAY" />
      <Association Name="TBL_PAYMENT_TBL_PAYMENTDETAIL" Member="TBL_PAYMENT" ThisKey="PAYMENT_ID" OtherKey="PAYMENT_ID" Type="TBL_PAYMENT" IsForeignKey="true" />
      <Association Name="TBL_SCHOOLYEAR_TBL_PAYMENTDETAIL" Member="TBL_SCHOOLYEAR" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_SCHOOLYEAR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SCHEDULETIME" Member="TBL_SCHEDULETIMEs">
    <Type Name="TBL_SCHEDULETIME">
      <Column Name="TIME_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TIME_START" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TIME_END" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_SCHEDULETIME_TBL_TEACHERSCHEDULE" Member="TBL_TEACHERSCHEDULEs" ThisKey="TIME_ID" OtherKey="TIME_ID" Type="TBL_TEACHERSCHEDULE" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SCHOOLYEAR" Member="TBL_SCHOOLYEARs">
    <Type Name="TBL_SCHOOLYEAR">
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_SCHOOLYEAR_TBL_PAYMENTDETAIL" Member="TBL_PAYMENTDETAILs" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_PAYMENTDETAIL" />
      <Association Name="TBL_SCHOOLYEAR_TBL_STUDENT" Member="TBL_STUDENTs" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_STUDENT" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SECURITY" Member="TBL_SECURITies">
    <Type Name="TBL_SECURITY">
      <Column Name="SECU_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SECU_QUESTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SECU_ANSWER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_USER_TBL_SECURITY" Member="TBL_USER" ThisKey="USER_ID" OtherKey="USER_ID" Type="TBL_USER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STANDPAY" Member="TBL_STANDPAYs">
    <Type Name="TBL_STANDPAY">
      <Column Name="STANDPAY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_PAYMENTDETAIL_TBL_STANDPAY" Member="TBL_PAYMENTDETAIL" ThisKey="PD_ID" OtherKey="PD_ID" Type="TBL_PAYMENTDETAIL" IsForeignKey="true" />
      <Association Name="TBL_STUDENT_TBL_STANDPAY" Member="TBL_STUDENT" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STUDENT" Member="TBL_STUDENTs">
    <Type Name="TBL_STUDENT">
      <Column Name="ST_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_YEARLEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ST_AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ST_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_BPSYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_BPDIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_STUDENT_TBL_BMICOMP" Member="TBL_BMICOMPs" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_BMICOMP" />
      <Association Name="TBL_STUDENT_TBL_GRADE" Member="TBL_GRADEs" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_GRADE" />
      <Association Name="TBL_STUDENT_TBL_STANDPAY" Member="TBL_STANDPAYs" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STANDPAY" />
      <Association Name="TBL_STUDENT_TBL_STUDBOOK" Member="TBL_STUDBOOKs" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDBOOK" />
      <Association Name="TBL_SCHOOLYEAR_TBL_STUDENT" Member="TBL_SCHOOLYEAR" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_SCHOOLYEAR" IsForeignKey="true" />
      <Association Name="TBL_PARENT_TBL_STUDENT" Member="TBL_PARENT" ThisKey="P_ID" OtherKey="P_ID" Type="TBL_PARENT" IsForeignKey="true" />
      <Association Name="TBL_SECTION_TBL_STUDENT" Member="TBL_SECTION" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_SECTION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SUBJECT" Member="TBL_SUBJECTs">
    <Type Name="TBL_SUBJECT">
      <Column Name="SUBJECT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TBL_SUBJECT_TBL_GRADE" Member="TBL_GRADEs" ThisKey="SUBJECT_ID" OtherKey="SUBJECT_ID" Type="TBL_GRADE" />
      <Association Name="TBL_SUBJECT_TBL_TEACHER" Member="TBL_TEACHERs" ThisKey="SUBJECT_ID" OtherKey="SUBJECT_ID" Type="TBL_TEACHER" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_TEACHER" Member="TBL_TEACHERs">
    <Type Name="TBL_TEACHER">
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="T_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="T_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="T_CONTACTNUMBER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SUBJECT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_TEACHER_TBL_THRINTERMEDIARYSEC" Member="TBL_THRINTERMEDIARYSECs" ThisKey="T_ID" OtherKey="T_ID" Type="TBL_THRINTERMEDIARYSEC" />
      <Association Name="TBL_TEACHER_TBL_SECTION" Member="TBL_SECTIONs" ThisKey="T_ID" OtherKey="T_ID" Type="TBL_SECTION" />
      <Association Name="TBL_SUBJECT_TBL_TEACHER" Member="TBL_SUBJECT" ThisKey="SUBJECT_ID" OtherKey="SUBJECT_ID" Type="TBL_SUBJECT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_THRINTERMEDIARYSEC" Member="TBL_THRINTERMEDIARYSECs">
    <Type Name="TBL_THRINTERMEDIARYSEC">
      <Column Name="THRANDSEC_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="T_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_TEACHER_TBL_THRINTERMEDIARYSEC" Member="TBL_TEACHER" ThisKey="T_ID" OtherKey="T_ID" Type="TBL_TEACHER" IsForeignKey="true" />
      <Association Name="TBL_SECTION_TBL_THRINTERMEDIARYSEC" Member="TBL_SECTION" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_SECTION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USERS" Member="TBL_USERs">
    <Type Name="TBL_USER">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_DATEADDED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_CREATOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="TBL_USER_TBL_SECURITY" Member="TBL_SECURITies" ThisKey="USER_ID" OtherKey="USER_ID" Type="TBL_SECURITY" />
      <Association Name="TBL_USERTYPE_TBL_USER" Member="TBL_USERTYPE" ThisKey="USER_TYPEID" OtherKey="USER_TYPEID" Type="TBL_USERTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_BMIRES" Member="View_BMIREs">
    <Type Name="View_BMIRE">
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BMI_HWRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BMI_BPRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_User" Member="View_Users">
    <Type Name="View_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[ISACTIVE?]" Member="ISACTIVE_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USERTYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_CombSchedule" Member="View_CombSchedules">
    <Type Name="View_CombSchedule">
      <Column Name="TIME_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SCHEDULE" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_GetTHNAME" Member="View_GetTHNAMEs">
    <Type Name="View_GetTHNAME">
      <Column Name="Fullname" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_Requirment" Member="View_Requirments">
    <Type Name="View_Requirment">
      <Column Name="[STUDENT NAME]" Member="STUDENT_NAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_Student1" Member="View_Student1s">
    <Type Name="View_Student1">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_STUDENTPROFILE" Member="View_STUDENTPROFILEs">
    <Type Name="View_STUDENTPROFILE">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[YEAR LEVEL]" Member="YEAR_LEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[ISACTIVE?]" Member="ISACTIVE_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="BP_SYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BP_DIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[PARENT ID]" Member="PARENT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OCCUPATION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[SCHOOLYEAR ID]" Member="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[SECTION ID]" Member="SECTION_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SECTION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_THTOSCHED" Member="View_THTOSCHEDs">
    <Type Name="View_THTOSCHED">
      <Column Name="[Teacher Name]" Member="Teacher_Name" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_TEACHERSCHEDULE" Member="TBL_TEACHERSCHEDULEs">
    <Type Name="TBL_TEACHERSCHEDULE">
      <Column Name="TSCHED_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEARCHER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUBJECT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TIME_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_SCHEDULETIME_TBL_TEACHERSCHEDULE" Member="TBL_SCHEDULETIME" ThisKey="TIME_ID" OtherKey="TIME_ID" Type="TBL_SCHEDULETIME" IsForeignKey="true" />
      <Association Name="TBL_SECTION_TBL_TEACHERSCHEDULE" Member="TBL_SECTION" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_SECTION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SECTION" Member="TBL_SECTIONs">
    <Type Name="TBL_SECTION">
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SEC_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SEC_CAPACITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="T_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEC_YEARLEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_SECTION_TBL_STUDENT" Member="TBL_STUDENTs" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_STUDENT" />
      <Association Name="TBL_SECTION_TBL_THRINTERMEDIARYSEC" Member="TBL_THRINTERMEDIARYSECs" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_THRINTERMEDIARYSEC" />
      <Association Name="TBL_SECTION_TBL_TEACHERSCHEDULE" Member="TBL_TEACHERSCHEDULEs" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_TEACHERSCHEDULE" />
      <Association Name="TBL_TEACHER_TBL_SECTION" Member="TBL_TEACHER" ThisKey="T_ID" OtherKey="T_ID" Type="TBL_TEACHER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STUDBOOKS" Member="TBL_STUDBOOKs">
    <Type Name="TBL_STUDBOOK">
      <Column Name="STUDBOOKS_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="B_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RETURNDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBL_STUDENT_TBL_STUDBOOK" Member="TBL_STUDENT" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDENT" IsForeignKey="true" />
      <Association Name="TBL_BOOK_TBL_STUDBOOK" Member="TBL_BOOK" ThisKey="B_ID" OtherKey="B_ID" Type="TBL_BOOK" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_ACCOUNTRECOVERY" Method="SP_ACCOUNTRECOVERY">
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SECU_QUESTION" Parameter="sECU_QUESTION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SECU_ANSWER" Parameter="sECU_ANSWER" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_ACCOUNTRECOVERYResult">
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SECU_QUESTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SECU_ANSWER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ST_CURRENTID" Method="ST_CURRENTID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BMISEARCH" Method="SP_BMISEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_BMISEARCHResult">
      <Column Name="[STUDENT NAME]" Member="STUDENT_NAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="[BODY MASS INDEX]" Member="BODY_MASS_INDEX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BLOODPRESSURE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_BOOKSEARCH" Method="SP_BOOKSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_BOOKSEARCHResult">
      <Column Name="B_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKDESC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B_AUTHOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="B_PUBLISHED" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_BOOKSSAVE" Method="SP_BOOKSSAVE">
    <Parameter Name="B_BOOKNAME" Parameter="b_BOOKNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_BOOKDESC" Parameter="b_BOOKDESC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BOOK_YEARLEVEL" Parameter="bOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_AUTHOR" Parameter="b_AUTHOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_PUBLISHED" Parameter="b_PUBLISHED" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BOOKSUPDATE" Method="SP_BOOKSUPDATE">
    <Parameter Name="B_ID" Parameter="b_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="B_BOOKNAME" Parameter="b_BOOKNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_BOOKDESC" Parameter="b_BOOKDESC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BOOK_YEARLEVEL" Parameter="bOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_AUTHOR" Parameter="b_AUTHOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_PUBLISHED" Parameter="b_PUBLISHED" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BOOKVIEW" Method="SP_BOOKVIEW">
    <ElementType Name="SP_BOOKVIEWResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BOOK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[YEAR LEVEL]" Member="YEAR_LEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AUTHOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PUBLISHED" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CHANGEDEFAULTPASS" Method="SP_CHANGEDEFAULTPASS">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CHANGEUSERPASS" Method="SP_CHANGEUSERPASS">
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PAYDETVIEW" Method="SP_PAYDETVIEW">
    <ElementType Name="SP_PAYDETVIEWResult">
      <Column Name="PD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTFOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTAMOUNT" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PAYMENTSAVE" Method="SP_PAYMENTSAVE">
    <Parameter Name="PAYMENT_NAME" Parameter="pAYMENT_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PAYMENT_DESC" Parameter="pAYMENT_DESC" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PAYMENTVIEW" Method="SP_PAYMENTVIEW">
    <ElementType Name="SP_PAYMENTVIEWResult">
      <Column Name="PAYMENT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PAYSAVE" Method="SP_PAYSAVE">
    <Parameter Name="PAYMENTFOR" Parameter="pAYMENTFOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PAYMENTAMOUNT" Parameter="pAYMENTAMOUNT" Type="System.Decimal" DbType="Money" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PAYMENT_ID" Parameter="pAYMENT_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PAYSEARCH" Method="SP_PAYSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_PAYSEARCHResult">
      <Column Name="PD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTFOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTAMOUNT" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PAYUPDATE" Method="SP_PAYUPDATE">
    <Parameter Name="PD_ID" Parameter="pD_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PAYMENTFOR" Parameter="pAYMENTFOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PAYMENTAMOUNT" Parameter="pAYMENTAMOUNT" Type="System.Decimal" DbType="Money" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SAVETIME" Method="SP_SAVETIME">
    <Parameter Name="TIME_START" Parameter="tIME_START" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TIME_END" Parameter="tIME_END" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SECTIONUPDATE" Method="SP_SECTIONUPDATE">
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEC_NAME" Parameter="sEC_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_CAPACITY" Parameter="sEC_CAPACITY" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_ID" Parameter="t_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="T_FIRSTNAME" Parameter="t_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_MIDDLENAME" Parameter="t_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_LASTNAME" Parameter="t_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SECUSAVE" Method="SP_SECUSAVE">
    <Parameter Name="SECU_QUESTION" Parameter="sECU_QUESTION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SECU_ANSWER" Parameter="sECU_ANSWER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_STREQSEARCH" Method="SP_STREQSEARCH">
    <Parameter Name="SEARCH_KEY" Parameter="sEARCH_KEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_STREQSEARCHResult">
      <Column Name="[STUDENT NAME]" Member="STUDENT_NAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_STSAVE" Method="SP_STSAVE">
    <Parameter Name="ST_CURRENTID" Parameter="sT_CURRENTID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FIRSTNAME" Parameter="sT_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_MIDDLENAME" Parameter="sT_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_LASTNAME" Parameter="sT_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_YEARLEVEL" Parameter="sT_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_BIRTHDATE" Parameter="sT_BIRTHDATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ST_AGE" Parameter="sT_AGE" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BIRTHPLACE" Parameter="sT_BIRTHPLACE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_ADDRESS" Parameter="sT_ADDRESS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GENDER" Parameter="sT_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_HEIGHT" Parameter="sT_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_WEIGHT" Parameter="sT_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_BPSYSTOLIC" Parameter="sT_BPSYSTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BPDIASTOLIC" Parameter="sT_BPDIASTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_FORM137" Parameter="sT_FORM137" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FORM138" Parameter="sT_FORM138" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GOODMORAL" Parameter="sT_GOODMORAL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_NSO" Parameter="sT_NSO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NAME" Parameter="nAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_CONTACT" Parameter="p_CONTACT" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_OCCUPATION" Parameter="p_OCCUPATION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_STSEARCH" Method="SP_STSEARCH">
    <Parameter Name="SEARCH_KEY" Parameter="sEARCH_KEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_STSEARCHResult">
      <Column Name="ST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_YEARLEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ST_AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ST_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_BPSYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_BPDIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_STUPDATE" Method="SP_STUPDATE">
    <Parameter Name="ST_CURRENTID" Parameter="sT_CURRENTID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FIRSTNAME" Parameter="sT_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_MIDDLENAME" Parameter="sT_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_LASTNAME" Parameter="sT_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_YEARLEVEL" Parameter="sT_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_BIRTHDATE" Parameter="sT_BIRTHDATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ST_AGE" Parameter="sT_AGE" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BIRTHPLACE" Parameter="sT_BIRTHPLACE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_ADDRESS" Parameter="sT_ADDRESS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GENDER" Parameter="sT_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ISACTIVE" Parameter="iSACTIVE" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ST_HEIGHT" Parameter="sT_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_WEIGHT" Parameter="sT_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_BPSYSTOLIC" Parameter="sT_BPSYSTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BPDIASTOLIC" Parameter="sT_BPDIASTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_FORM137" Parameter="sT_FORM137" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FORM138" Parameter="sT_FORM138" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GOODMORAL" Parameter="sT_GOODMORAL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_NSO" Parameter="sT_NSO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_ID" Parameter="p_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="P_NAME" Parameter="p_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_CONTACT" Parameter="p_CONTACT" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_OCCUPATION" Parameter="p_OCCUPATION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEC_NAME" Parameter="sEC_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SCHOOLYEAR" Parameter="sCHOOLYEAR" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_STVIEW" Method="SP_STVIEW">
    <ElementType Name="SP_STVIEWResult">
      <Column Name="ST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_YEARLEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ST_AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ST_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_BPSYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_BPDIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SUBSAVE" Method="SP_SUBSAVE">
    <Parameter Name="SUBJECTNAME" Parameter="sUBJECTNAME" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SUBSEARCH" Method="SP_SUBSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_SUBSEARCHResult">
      <Column Name="SUBJECT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SUBUPDATE" Method="SP_SUBUPDATE">
    <Parameter Name="SUBJECT_ID" Parameter="sUBJECT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUBJECTNAME" Parameter="sUBJECTNAME" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SUBVIEW" Method="SP_SUBVIEW">
    <ElementType Name="SP_SUBVIEWResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUBJECT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SYSAVE" Method="SP_SYSAVE">
    <Parameter Name="SCHOOLYEAR" Parameter="sCHOOLYEAR" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SYUPDATE" Method="SP_SYUPDATE">
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SCHOOLYEAR" Parameter="sCHOOLYEAR" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SYVIEW" Method="SP_SYVIEW">
    <ElementType Name="SP_SYVIEWResult">
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_TEACHERSAVE" Method="SP_TEACHERSAVE">
    <Parameter Name="T_FIRSTNAME" Parameter="t_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_MIDDLENAME" Parameter="t_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_LASTNAME" Parameter="t_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_CONTACTNUMBER" Parameter="t_CONTACTNUMBER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SUBJECT_ID" Parameter="sUBJECT_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_TEACHERSEARCH" Method="SP_TEACHERSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_TEACHERSEARCHResult">
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="T_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="T_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="T_CONTACTNUMBER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SUBJECT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_TEACHERUPDATE" Method="SP_TEACHERUPDATE">
    <Parameter Name="T_ID" Parameter="t_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="T_FIRSTNAME" Parameter="t_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_MIDDLENAME" Parameter="t_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_LASTNAME" Parameter="t_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ISACTIVE" Parameter="iSACTIVE" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="T_CONTACTNUMBER" Parameter="t_CONTACTNUMBER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SUBJECT_ID" Parameter="sUBJECT_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUBJECTNAME" Parameter="sUBJECTNAME" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_TEACHERVIEW" Method="SP_TEACHERVIEW">
    <ElementType Name="SP_TEACHERVIEWResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[ISACTIVE?]" Member="ISACTIVE_" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[CONTACT NUMBER]" Member="CONTACT_NUMBER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[SUBJECT ID]" Member="SUBJECT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUBJECT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_THSCHEDUPDATE" Method="SP_THSCHEDUPDATE">
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEC_NAME" Parameter="sEC_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TIME_ID" Parameter="tIME_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TIME_START" Parameter="tIME_START" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TIME_END" Parameter="tIME_END" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_USERSAVE" Method="SP_USERSAVE">
    <Parameter Name="USER_LASTNAME" Parameter="uSER_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_FIRSTNAME" Parameter="uSER_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_MIDDLENAME" Parameter="uSER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_CONTACTNO" Parameter="uSER_CONTACTNO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_CREATOR" Parameter="uSER_CREATOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_TYPE" Parameter="uSER_TYPE" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_IMAGE" Parameter="uSER_IMAGE" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_USERSEARCH" Method="SP_USERSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_USERSEARCHResult">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USER_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_DATEADDED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_CREATOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_USERUPDATE" Method="SP_USERUPDATE">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_LASTNAME" Parameter="uSER_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_FIRSTNAME" Parameter="uSER_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_MIDDLENAME" Parameter="uSER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ISACTIVE" Parameter="iSACTIVE" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="USER_IMAGE" Parameter="uSER_IMAGE" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_USERVIEW" Method="SP_USERVIEW">
    <ElementType Name="SP_USERVIEWResult">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USER_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_DATEADDED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_CREATOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VERIFYPASSWORD" Method="SP_VERIFYPASSWORD">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_VERIFYPASSWORDResult">
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VIEWBMI" Method="SP_VIEWBMI">
    <ElementType Name="SP_VIEWBMIResult">
      <Column Name="[STUDENT NAME]" Member="STUDENT_NAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="[BODY MASS INDEX]" Member="BODY_MASS_INDEX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BLOODPRESSURE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VIEWTIME" Method="SP_VIEWTIME">
    <ElementType Name="SP_VIEWTIMEResult">
      <Column Name="TIME_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TIME_START" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TIME_END" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_THSCHEDSAVE" Method="SP_THSCHEDSAVE">
    <Parameter Name="TEARCHER" Parameter="tEARCHER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SUBJECT" Parameter="sUBJECT" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TIME_ID" Parameter="tIME_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_THSCHEDVIEW" Method="SP_THSCHEDVIEW">
    <ElementType Name="SP_THSCHEDVIEWResult">
      <Column Name="TSCHED_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TEARCHER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SECTION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TIME_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHEDULE" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_THSCHEDSEARCH" Method="SP_THSCHEDSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_THSCHEDSEARCHResult">
      <Column Name="TSCHED_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TEARCHER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SECTION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TIME_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHEDULE" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_EXISTSEC" Method="SP_EXISTSEC">
    <Parameter Name="TEARCHER" Parameter="tEARCHER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_EXISTSECResult">
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SECTIONSAVE" Method="SP_SECTIONSAVE">
    <Parameter Name="SEC_NAME" Parameter="sEC_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_CAPACITY" Parameter="sEC_CAPACITY" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="T_ID" Parameter="t_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEC_YEARLEVEL" Parameter="sEC_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SECVIEW" Method="SP_SECVIEW">
    <ElementType Name="SP_SECVIEWResult">
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SECTION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CAPACITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[YEAR LEVEL]" Member="YEAR_LEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ADVISORY" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VIEWSTUDBOOKS" Method="SP_VIEWSTUDBOOKS">
    <ElementType Name="SP_VIEWSTUDBOOKSResult">
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[STUDENT NAME]" Member="STUDENT_NAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="B_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BOOK" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RETURNDATE" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>