<?xml version="1.0" encoding="utf-8"?><Database Name="ANS_DATABASE" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=ANS_DATABASE;Integrated Security=True" SettingsObjectName="ABELLANA_NATIONAL_SCHOOL_FINAL.Properties.Settings" SettingsPropertyName="ANS_DATABASEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_BMICOMP" Member="TBL_BMICOMPs">
    <Type Name="TBL_BMICOMP">
      <Column Name="BMI_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BMI_HWRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BMI_BPRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_STUDENT_TBL_BMICOMP" Member="TBL_STUDENT" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USERTYPE" Member="TBL_USERTYPEs">
    <Type Name="TBL_USERTYPE">
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_TYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_USERTYPE_TBL_USER" Member="TBL_USERs" ThisKey="USER_TYPEID" OtherKey="USER_TYPEID" Type="TBL_USER" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_BOOKS" Member="TBL_BOOKs">
    <Type Name="TBL_BOOK">
      <Column Name="B_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="B_BOOKNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKDESC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_GRADE" Member="TBL_GRADEs">
    <Type Name="TBL_GRADE">
      <Column Name="GRADE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GRADEPERIOD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GRADE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUBJECT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_STUDENT_TBL_GRADE" Member="TBL_STUDENT" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDENT" IsForeignKey="true" />
      <Association Name="TBL_SUBJECT_TBL_GRADE" Member="TBL_SUBJECT" ThisKey="SUBJECT_ID" OtherKey="SUBJECT_ID" Type="TBL_SUBJECT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PARENT" Member="TBL_PARENTs">
    <Type Name="TBL_PARENT">
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="P_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_OCCUPATION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TBL_PARENT_TBL_STUDENT" Member="TBL_STUDENTs" ThisKey="P_ID" OtherKey="P_ID" Type="TBL_STUDENT" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PAYMENT" Member="TBL_PAYMENTs">
    <Type Name="TBL_PAYMENT">
      <Column Name="PAYMENT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PAYMENT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_PAYMENT_TBL_PAYMENTDETAIL" Member="TBL_PAYMENTDETAILs" ThisKey="PAYMENT_ID" OtherKey="PAYMENT_ID" Type="TBL_PAYMENTDETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PAYMENTDETAILS" Member="TBL_PAYMENTDETAILs">
    <Type Name="TBL_PAYMENTDETAIL">
      <Column Name="PD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PAYMENTFOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTAMOUNT" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAYMENT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_PAYMENTDETAIL_TBL_STANDPAY" Member="TBL_STANDPAYs" ThisKey="PD_ID" OtherKey="PD_ID" Type="TBL_STANDPAY" />
      <Association Name="TBL_PAYMENT_TBL_PAYMENTDETAIL" Member="TBL_PAYMENT" ThisKey="PAYMENT_ID" OtherKey="PAYMENT_ID" Type="TBL_PAYMENT" IsForeignKey="true" />
      <Association Name="TBL_SCHOOLYEAR_TBL_PAYMENTDETAIL" Member="TBL_SCHOOLYEAR" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_SCHOOLYEAR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SCHOOLYEAR" Member="TBL_SCHOOLYEARs">
    <Type Name="TBL_SCHOOLYEAR">
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_SCHOOLYEAR_TBL_PAYMENTDETAIL" Member="TBL_PAYMENTDETAILs" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_PAYMENTDETAIL" />
      <Association Name="TBL_SCHOOLYEAR_TBL_STUDENT" Member="TBL_STUDENTs" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_STUDENT" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SECTION" Member="TBL_SECTIONs">
    <Type Name="TBL_SECTION">
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SEC_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SEC_CAPACITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TBL_SECTION_TBL_STUDENT" Member="TBL_STUDENTs" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_STUDENT" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SECURITY" Member="TBL_SECURITies">
    <Type Name="TBL_SECURITY">
      <Column Name="SECU_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SECU_QUESTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SECU_ANSWER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_USER_TBL_SECURITY" Member="TBL_USER" ThisKey="USER_ID" OtherKey="USER_ID" Type="TBL_USER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STANDPAY" Member="TBL_STANDPAYs">
    <Type Name="TBL_STANDPAY">
      <Column Name="STANDPAY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TBL_PAYMENTDETAIL_TBL_STANDPAY" Member="TBL_PAYMENTDETAIL" ThisKey="PD_ID" OtherKey="PD_ID" Type="TBL_PAYMENTDETAIL" IsForeignKey="true" />
      <Association Name="TBL_STUDENT_TBL_STANDPAY" Member="TBL_STUDENT" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_STUDENT" Member="TBL_STUDENTs">
    <Type Name="TBL_STUDENT">
      <Column Name="ST_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_YEARLEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ST_AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ST_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_BPSYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_BPDIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_STUDENT_TBL_BMICOMP" Member="TBL_BMICOMPs" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_BMICOMP" />
      <Association Name="TBL_STUDENT_TBL_GRADE" Member="TBL_GRADEs" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_GRADE" />
      <Association Name="TBL_STUDENT_TBL_STANDPAY" Member="TBL_STANDPAYs" ThisKey="ST_CURRENTID" OtherKey="ST_CURRENTID" Type="TBL_STANDPAY" />
      <Association Name="TBL_SCHOOLYEAR_TBL_STUDENT" Member="TBL_SCHOOLYEAR" ThisKey="SCHOOLYEAR_ID" OtherKey="SCHOOLYEAR_ID" Type="TBL_SCHOOLYEAR" IsForeignKey="true" />
      <Association Name="TBL_SECTION_TBL_STUDENT" Member="TBL_SECTION" ThisKey="SEC_ID" OtherKey="SEC_ID" Type="TBL_SECTION" IsForeignKey="true" />
      <Association Name="TBL_PARENT_TBL_STUDENT" Member="TBL_PARENT" ThisKey="P_ID" OtherKey="P_ID" Type="TBL_PARENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SUBJECT" Member="TBL_SUBJECTs">
    <Type Name="TBL_SUBJECT">
      <Column Name="SUBJECT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SUBJECT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TBL_SUBJECT_TBL_GRADE" Member="TBL_GRADEs" ThisKey="SUBJECT_ID" OtherKey="SUBJECT_ID" Type="TBL_GRADE" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USERS" Member="TBL_USERs">
    <Type Name="TBL_USER">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_DATEADDED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_CREATOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="TBL_USER_TBL_SECURITY" Member="TBL_SECURITies" ThisKey="USER_ID" OtherKey="USER_ID" Type="TBL_SECURITY" />
      <Association Name="TBL_USERTYPE_TBL_USER" Member="TBL_USERTYPE" ThisKey="USER_TYPEID" OtherKey="USER_TYPEID" Type="TBL_USERTYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_BMIRES" Member="View_BMIREs">
    <Type Name="View_BMIRE">
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BMI_HWRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BMI_BPRESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_User" Member="View_Users">
    <Type Name="View_User">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_Requirment" Member="View_Requirments">
    <Type Name="View_Requirment">
      <Column Name="[STUDENT NAME]" Member="STUDENT_NAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_Student1" Member="View_Student1s">
    <Type Name="View_Student1">
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_STUDENTPROFILE" Member="View_STUDENTPROFILEs">
    <Type Name="View_STUDENTPROFILE">
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_YEARLEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ST_AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ST_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_BPSYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_BPDIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_OCCUPATION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SEC_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SP_ACCOUNTRECOVERY" Method="SP_ACCOUNTRECOVERY">
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SECU_QUESTION" Parameter="sECU_QUESTION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SECU_ANSWER" Parameter="sECU_ANSWER" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_ACCOUNTRECOVERYResult">
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SECU_QUESTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SECU_ANSWER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ST_CURRENTID" Method="ST_CURRENTID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BOOKSEARCH" Method="SP_BOOKSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_BOOKSEARCHResult">
      <Column Name="B_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKDESC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CHANGEDEFAULTPASS" Method="SP_CHANGEDEFAULTPASS">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CHANGEUSERPASS" Method="SP_CHANGEUSERPASS">
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PAYDETVIEW" Method="SP_PAYDETVIEW">
    <ElementType Name="SP_PAYDETVIEWResult">
      <Column Name="PD_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTFOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENTAMOUNT" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PAYMENTSAVE" Method="SP_PAYMENTSAVE">
    <Parameter Name="PAYMENT_NAME" Parameter="pAYMENT_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PAYMENT_DESC" Parameter="pAYMENT_DESC" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PAYMENTVIEW" Method="SP_PAYMENTVIEW">
    <ElementType Name="SP_PAYMENTVIEWResult">
      <Column Name="PAYMENT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PAYMENT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_DESC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PAYSAVE" Method="SP_PAYSAVE">
    <Parameter Name="PAYMENTFOR" Parameter="pAYMENTFOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PAYMENTAMOUNT" Parameter="pAYMENTAMOUNT" Type="System.Decimal" DbType="Money" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PAYMENT_ID" Parameter="pAYMENT_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PAYUPDATE" Method="SP_PAYUPDATE">
    <Parameter Name="PD_ID" Parameter="pD_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PAYMENTFOR" Parameter="pAYMENTFOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PAYMENTAMOUNT" Parameter="pAYMENTAMOUNT" Type="System.Decimal" DbType="Money" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SECTIONSAVE" Method="SP_SECTIONSAVE">
    <Parameter Name="SEC_NAME" Parameter="sEC_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_CAPACITY" Parameter="sEC_CAPACITY" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SECUSAVE" Method="SP_SECUSAVE">
    <Parameter Name="SECU_QUESTION" Parameter="sECU_QUESTION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SECU_ANSWER" Parameter="sECU_ANSWER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SECVIEW" Method="SP_SECVIEW">
    <ElementType Name="SP_SECVIEWResult">
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SEC_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SEC_CAPACITY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_STREQSEARCH" Method="SP_STREQSEARCH">
    <Parameter Name="SEARCH_KEY" Parameter="sEARCH_KEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_STREQSEARCHResult">
      <Column Name="[STUDENT NAME]" Member="STUDENT_NAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_STSAVE" Method="SP_STSAVE">
    <Parameter Name="ST_CURRENTID" Parameter="sT_CURRENTID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FIRSTNAME" Parameter="sT_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_MIDDLENAME" Parameter="sT_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_LASTNAME" Parameter="sT_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_YEARLEVEL" Parameter="sT_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_BIRTHDATE" Parameter="sT_BIRTHDATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ST_AGE" Parameter="sT_AGE" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BIRTHPLACE" Parameter="sT_BIRTHPLACE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_ADDRESS" Parameter="sT_ADDRESS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GENDER" Parameter="sT_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_HEIGHT" Parameter="sT_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_WEIGHT" Parameter="sT_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_BPSYSTOLIC" Parameter="sT_BPSYSTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BPDIASTOLIC" Parameter="sT_BPDIASTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_FORM137" Parameter="sT_FORM137" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FORM138" Parameter="sT_FORM138" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GOODMORAL" Parameter="sT_GOODMORAL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_NSO" Parameter="sT_NSO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NAME" Parameter="nAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_CONTACT" Parameter="p_CONTACT" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_OCCUPATION" Parameter="p_OCCUPATION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_STSEARCH" Method="SP_STSEARCH">
    <Parameter Name="SEARCH_KEY" Parameter="sEARCH_KEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_STSEARCHResult">
      <Column Name="ST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_YEARLEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ST_AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ST_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_BPSYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_BPDIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_STUPDATE" Method="SP_STUPDATE">
    <Parameter Name="ST_CURRENTID" Parameter="sT_CURRENTID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FIRSTNAME" Parameter="sT_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_MIDDLENAME" Parameter="sT_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_LASTNAME" Parameter="sT_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_YEARLEVEL" Parameter="sT_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_BIRTHDATE" Parameter="sT_BIRTHDATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ST_AGE" Parameter="sT_AGE" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BIRTHPLACE" Parameter="sT_BIRTHPLACE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_ADDRESS" Parameter="sT_ADDRESS" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GENDER" Parameter="sT_GENDER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ISACTIVE" Parameter="iSACTIVE" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ST_HEIGHT" Parameter="sT_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_WEIGHT" Parameter="sT_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" />
    <Parameter Name="ST_BPSYSTOLIC" Parameter="sT_BPSYSTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_BPDIASTOLIC" Parameter="sT_BPDIASTOLIC" Type="System.Int32" DbType="Int" />
    <Parameter Name="ST_FORM137" Parameter="sT_FORM137" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_FORM138" Parameter="sT_FORM138" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_GOODMORAL" Parameter="sT_GOODMORAL" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_NSO" Parameter="sT_NSO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_ID" Parameter="p_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="P_NAME" Parameter="p_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_CONTACT" Parameter="p_CONTACT" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="P_OCCUPATION" Parameter="p_OCCUPATION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEC_NAME" Parameter="sEC_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SCHOOLYEAR" Parameter="sCHOOLYEAR" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_STVIEW" Method="SP_STVIEW">
    <ElementType Name="SP_STVIEWResult">
      <Column Name="ST_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_CURRENTID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ST_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_YEARLEVEL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHDATE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ST_AGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ST_BIRTHPLACE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_ADDRESS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GENDER" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ST_HEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_WEIGHT" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ST_BPSYSTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_BPDIASTOLIC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ST_FORM137" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_FORM138" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_GOODMORAL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ST_NSO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SYSAVE" Method="SP_SYSAVE">
    <Parameter Name="SCHOOLYEAR" Parameter="sCHOOLYEAR" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SYUPDATE" Method="SP_SYUPDATE">
    <Parameter Name="SCHOOLYEAR_ID" Parameter="sCHOOLYEAR_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SCHOOLYEAR" Parameter="sCHOOLYEAR" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SYVIEW" Method="SP_SYVIEW">
    <ElementType Name="SP_SYVIEWResult">
      <Column Name="SCHOOLYEAR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHOOLYEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_USERSAVE" Method="SP_USERSAVE">
    <Parameter Name="USER_LASTNAME" Parameter="uSER_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_FIRSTNAME" Parameter="uSER_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_MIDDLENAME" Parameter="uSER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_CONTACTNO" Parameter="uSER_CONTACTNO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_CREATOR" Parameter="uSER_CREATOR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_TYPE" Parameter="uSER_TYPE" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_IMAGE" Parameter="uSER_IMAGE" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_USERSEARCH" Method="SP_USERSEARCH">
    <Parameter Name="SEARCHKEY" Parameter="sEARCHKEY" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_USERSEARCHResult">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USER_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_DATEADDED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_CREATOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_USERUPDATE" Method="SP_USERUPDATE">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_LASTNAME" Parameter="uSER_LASTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_FIRSTNAME" Parameter="uSER_FIRSTNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_MIDDLENAME" Parameter="uSER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="USER_USERNAME" Parameter="uSER_USERNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ISACTIVE" Parameter="iSACTIVE" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="USER_IMAGE" Parameter="uSER_IMAGE" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_USERVIEW" Method="SP_USERVIEW">
    <ElementType Name="SP_USERVIEWResult">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USER_LASTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_FIRSTNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_MIDDLENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_USERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_CONTACT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ISACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_DATEADDED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_CREATOR" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="USER_TYPEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USER_IMAGE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VERIFYPASSWORD" Method="SP_VERIFYPASSWORD">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="USER_PASSWORD" Parameter="uSER_PASSWORD" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SP_VERIFYPASSWORDResult">
      <Column Name="USER_PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VIEWBMI" Method="SP_VIEWBMI">
    <ElementType Name="SP_VIEWBMIResult">
      <Column Name="FULLNAME" Type="System.String" DbType="VarChar(152)" CanBeNull="true" />
      <Column Name="[BMI RESULT]" Member="BMI_RESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[BLOODPRESSURE RESULT]" Member="BLOODPRESSURE_RESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_BOOKSSAVE" Method="SP_BOOKSSAVE">
    <Parameter Name="B_BOOKNAME" Parameter="b_BOOKNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_BOOKDESC" Parameter="b_BOOKDESC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BOOK_YEARLEVEL" Parameter="bOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BOOKSUPDATE" Method="SP_BOOKSUPDATE">
    <Parameter Name="B_ID" Parameter="b_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="B_BOOKNAME" Parameter="b_BOOKNAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="B_BOOKDESC" Parameter="b_BOOKDESC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ST_CURRENTID" Parameter="sT_CURRENTID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BOOK_YEARLEVEL" Parameter="bOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BOOKVIEW" Method="SP_BOOKVIEW">
    <ElementType Name="SP_BOOKVIEWResult">
      <Column Name="B_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="B_BOOKDESC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BOOK_YEARLEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SECTIONUPDATE" Method="SP_SECTIONUPDATE">
    <Parameter Name="SEC_ID" Parameter="sEC_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEC_NAME" Parameter="sEC_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SEC_CAPACITY" Parameter="sEC_CAPACITY" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>